version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-init
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /opt/mlops-storage/mlflow/artifacts:/mlflow-artifacts:ro
    command: >
      bash -c "airflow db migrate"
    restart: "no"

  airflow-dag-processor:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-dag-processor
    depends_on:
      - postgres
      - airflow-init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /opt/mlops-storage/mlflow/artifacts:/mlflow-artifacts:ro
    command: dag-processor
    restart: unless-stopped

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    depends_on:
      - postgres
      - airflow-init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET}
      AIRFLOW__AUTH_MANAGER__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      AIRFLOW__AUTH_MANAGER__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "true"
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-webserver:8080/execution/"
      AIRFLOW__API__WORKERS: "1"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./simple_auth_manager_passwords.json:/opt/airflow/simple_auth_manager_passwords.json.generated
      - /opt/mlops-storage/mlflow/artifacts:/mlflow-artifacts:ro
    command: api-server --workers 1
    ports:
      - "8080:8080"
    restart: unless-stopped

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET}
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-webserver:8080/execution/"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /opt/mlops-storage/mlflow/artifacts:/mlflow-artifacts:ro
    command: scheduler
    restart: unless-stopped

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/mlflow
      --artifacts-destination /mlflow/artifacts
      --allowed-hosts "*"
    volumes:
      - /opt/mlops-storage/mlflow/artifacts:/mlflow/artifacts
    ports:
      - "5000:5000"
    restart: unless-stopped

  model-registry-api:
    build:
      context: ./model-registry-api
      dockerfile: Dockerfile
    container_name: model-registry-api
    env_file:
      - .env
    environment:
      REGISTRY_ROOT: /registry
      DVC_REGISTRY_ROOT: /app/storage/registry
      DVC_ENABLED: "true"
      DVC_REMOTE_NAME: origin
      DVC_AUTO_PUSH: "true"
      REGISTRY_API_TOKEN: ${REGISTRY_API_TOKEN}
      COMPARISON_PRIMARY_METRIC: f1_score
      COMPARISON_FALLBACK_METRIC: accuracy
    volumes:
      - /opt/mlops-storage/registry:/registry
      - /opt/mlops-storage/uploads:/registry/uploads
      - ./storage:/app/storage
      - ./.dvc:/app/.dvc
      - ./.git:/app/.git
    ports:
      - "8082:8082"
    restart: unless-stopped

  predict-api:
    build:
      context: ./predict-api
      dockerfile: Dockerfile
    container_name: predict-api
    env_file:
      - .env
    environment:
      REGISTRY_PRODUCTION_DIR: /registry/production
      MODEL_FILENAME: best_model.pth
      MODEL_METADATA_FILENAME: current_model.json
      MODEL_RESULTS_FILENAME: results.json
      IMG_SIZE: 224
      PREDICT_DEVICE: cpu
    volumes:
      - /opt/mlops-storage/registry:/registry:ro
    ports:
      - "8001:8001"
    restart: unless-stopped
  streamlit-app:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    container_name: streamlit-app
    depends_on:
      - predict-api
    environment:
      PREDICT_API_URL: http://predict-api:8001/predict
      HEALTH_API_URL: http://predict-api:8001/health
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  airflow_postgres_data: